//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Cliente
    {
        public int Id { get; set; }
        public int Cliente_id { get; set; }
        public string Nome { get; set; }
        public string Linha_CAP { get; set; }
        public string Mercado_CAP { get; set; }
        public string Cor { get; set; }
        public string Modal { get; set; }
        public string Mercado_VF { get; set; }
        public string Pais { get; set; }
        public Nullable<int> MercadoCAPId { get; set; }
        public Nullable<int> MercadoVFId { get; set; }
        public Nullable<int> LinhaCAPId { get; set; }
        public decimal percentual { get; set; }
        public string Porcentagem_Protocolo { get; set; }
        public string Volume_Protocolo { get; set; }
        public string Tonelada_Protocolo { get; set; }
    }
}
