//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_LinhaCAP
    {
        public int LinhaCAPId { get; set; }
        public string Linha_CAP { get; set; }
        public int MercadoCAPId { get; set; }
        public int MercadoVFId { get; set; }
    }
}
