//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_PlanoSemanal
    {
        public int Id { get; set; }
        public string Grau { get; set; }
        public Nullable<double> Espessura { get; set; }
        public Nullable<double> Volume { get; set; }
        public string PACOTE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
