//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Parametro
    {
        public int Id { get; set; }
        public string Chave { get; set; }
        public string Descricao { get; set; }
        public string Valor { get; set; }
    }
}
