//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForeCast : DbContext
    {
        public ForeCast()
            : base("name=ForeCast")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FC_LinhaCAP> FC_LinhaCAP { get; set; }
        public virtual DbSet<FC_MeioTransporte> FC_MeioTransporte { get; set; }
        public virtual DbSet<FC_MercadoCAP> FC_MercadoCAP { get; set; }
        public virtual DbSet<FC_MercadoVF> FC_MercadoVF { get; set; }
        public virtual DbSet<FC_Parametro> FC_Parametro { get; set; }
        public virtual DbSet<FC_PlanoEmbarque> FC_PlanoEmbarque { get; set; }
        public virtual DbSet<FC_quadrimestre> FC_quadrimestre { get; set; }
        public virtual DbSet<FC_Cliente> FC_Cliente { get; set; }
        public virtual DbSet<FC_BreakDown> FC_BreakDown { get; set; }
        public virtual DbSet<FC_PlanoSemanal> FC_PlanoSemanal { get; set; }
    }
}
