//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Cliente
    {
        public int Cliente_id { get; set; }
        public string Nome { get; set; }
        public string Linha_CAP { get; set; }
        public string Mercado_CAP { get; set; }
        public string Cor { get; set; }
        public string Modal { get; set; }
        public string Mercado_VF { get; set; }
        public string Pais { get; set; }
        public int MercadoCAPId { get; set; }
        public int MercadoVFId { get; set; }
        public int LinhaCAPId { get; set; }
    }
}
