//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_MeioTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_MeioTransporte()
        {
            this.FC_PlanoEmbarque = new HashSet<FC_PlanoEmbarque>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Icone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_PlanoEmbarque> FC_PlanoEmbarque { get; set; }
    }
}
