//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoEmbarque.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_PlanoEmbarque
    {
        public int Id { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Ano { get; set; }
        public double Valor { get; set; }
        public int PEA_Ano { get; set; }
        public int MeioTransporte_Id { get; set; }
        public int Cliente_Id { get; set; }
        public string Pacote { get; set; }
        public Nullable<System.DateTime> DataEmbarque { get; set; }
        public string Quadrimestre { get; set; }
        public Nullable<int> Contador { get; set; }
    }
}
