//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_quadrimestre
    {
        public int Id { get; set; }
        public string Chave { get; set; }
        public System.DateTime DTInicio { get; set; }
        public System.DateTime DTFimValor { get; set; }
    }
}
